language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: DLe5HqTbBmW2xrNV+82dIcXDlyqynARrjlDM9+BESwKK0vqC62gu18dqN0xvCZFgUJ2aca4184eSIOXsGiATsBt2niUtHfdC/gM7ldwqhLXDfofJYBTSjJVjpsjwovWj10J7QjPB3ODcrtOHBVyjDphtpGLjiHMOV7a6K/R8XNtsmfn9NvnDTygVcDqBcDttkMkaIaq7vCG0khgXVKDo+QBAUiLiXSNoMa9+qOa8dFluvnTIirOjnWHSkylKES3GZRYMWu642vE0amo8dGxgpwfJ9CRxom6w5pGGZzy8ZCld7ZP00TS4639Ewtwk6VmFQk0qMw1qVrPn4HrvTO391hIHhK4i6bjE/Ylh1tltMBGMMa7be0xKN6z6dg2KYMdz5Z35/pOJw5NsljD8JN4Rz3g+RV8VT2NiZf1TdSS/Hy3W2IdxZnM9TuiRDBIev/VGCLOk6Zzwg86T62UAFi8PRJbg2au6gM/n27l6OHiMmAge3glo53Wt/iT1Nrma+mbZD1gDqyG29C0eqY2GzDiMsETeqLZqpgGpqKv+v5P91Z5NUVWS3Gv5RFyng0evNRdMA+RE1qEJ+vOJpCujS5Bl024xR6BN1qcZTGeiOxf4Z1N/kWXRLnrAHXiJFpYn4LiDKOGZry0b41/N/HGeDR203sP6YKNbs8ZN0saic9bzheM=
  app: intense-lowlands-98053
  on:
    repo: LeoYuanjieLi/node-shopping-list-integration-tests
    branch: test-for-recipes
